const employees = [
  {
    id: 1,
    parentId: "",
    name: "Pema ji Hamad",
    positionName: "Farmer",
    wife: "Nandi bai Hamad",
    father: "Dallaji Hamad",
    mother: "",
    phone: "There was no Phone back then",
    email: "There was no email back then",
    sex: "Male",
    team: "",
    dob: "",
    dod: "",
    // location: "LA Branch",
    department: "",
    description:
      "Pemaji was probably born before 1920. He was a farmer by profession. He had about 24 bighas of land. They had Two sons and have Two daughters named Hiribai and ramibai. Pemaji died suddenly of a heart attack.",
    imageUrl:
      "https://cdn.dribbble.com/users/1223630/screenshots/8115260/media/8145a871d9c4d67ec06e047ccc6574b4.gif",
  },
  {
    id: 2,
    parentId: "1",
    name: "Mangilal ji Hamad",
    positionName: "Farmer",
    wife: "Kanku bai Hamad",
    father: "Pemaji Hamad",
    mother: "Nandi bai Hamad",
    phone: "They didnt have phone",
    email: "There was no Email back then",
    sex: "Male",
    team: "",
    // location: "LA Branch",
    department: "",
    description:
      "Mangilal ji was probably born before 1940. He was a farmer by profession. He had about 12 bighas of land. They had Three sons and had one daughter name Geeta who died of illness in her teens. Mangilalji died suddenly of a heart attack.",
    imageUrl:
      "https://cdn.dribbble.com/users/1223630/screenshots/8115260/media/8145a871d9c4d67ec06e047ccc6574b4.gif",
  },

  {
    id: 3,
    parentId: "1",
    name: "Kesha ji Hamad",
    positionName: "Farmer",
    wife: "Shanta bai Hamad",
    father: "Dallaji Hamad",
    mother: "Nandi bai Hamad",
    phone: "tel- 07296-261573",
    email: "There was no email back then",
    sex: "Male",
    team: "",
    dob: " 1948 or 1948 ",
    dod: "03/10/2019",
    department: "",
    description:
      " Kesaji was born around 1948. He was a farmer by profession. He had 12 bighas of land in his share. He has three sons and one daughter named Ramkanya.He completed his Studies till 5th standard. After a lot of struggle in his life, he bought another 21 bigha's of land. After that he gave the burden of farming to his son. And started taking interest in business and also did business for a few years. He was suffering from cancer in the year 2016 and died on 03/10/2019. ",
    imageUrl: "images/kesaji.jpg",
  },

  {
    id: 4,
    parentId: "3",
    name: "Narayan Hamad",
    positionName: "Farmer",
    wife: "Leela (Bhagu) bai Hamad",
    father: "Kesaji Hamad",
    mother: "Shanta bai Hamad",
    phone: "9993984609",
    email: "narayanhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "01/01/1968",
    dod: "live",
    // department: "Marketing",
    description:
      "Narayan hamad is born in 1968. He is the eldest son of Kesaji Hamad.He had three sons. He completed his Studies till 7th standard. He is a farmer by profession and has 2 sons.Narayan is living Separately He has 10 bigha's land",
    imageUrl: "images/narayan.jpg",
  },
  {
    id: 5,
    parentId: "3",
    name: "Mannalal Hamad",
    positionName: "Farmer",
    wife: "Leela Hamad",
    father: "Kesaji Hamad",
    mother: "Shanta Hamad",
    phone: "9981661574",
    email: "mannalalhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "01/01/1970",
    dod: "live",
    // department: "Marketing",
    description:
      "Mannalal hamad is born in 1970. He is the middle son of Kesaji Hamad.He completed his Studies till 6th standard. He is a farmer by profession and has One sons and one daughter named Durga .Mannalal And Gopal both brothers are living together in joint family. They have total 23 bigha's land",
    imageUrl: "images/manna.jpg",
  },
  {
    id: 6,
    parentId: "3",
    name: "Gopal Hamad",
    positionName: "Shopkeeper",
    wife: "Kanku Hamad",
    father: "Kesaji Hamad",
    mother: "Shanta Hamad",
    phone: "9993895094",
    email: "gopalhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "21/04/1974",
    dod: "live",
    // department: "Marketing",
    description:
      "Gopal hamad is born in 21/04/1974. He is the youngest son of Kesaji Hamad.He completed his graduation from DAVV in Commerce Stream .He is a Shopkeeper by profession. From the beginning ,he was very interested in business. In the year 2000 he opened a grocery Store and achieve many heights in in life while doing  business for many years. After that due to ill healt of his father he started taking interested in farming  and has One sons and Two daughter named Sarita and Pooja. .Gopal And Mannalal both brothers are living together in joint family. They have total 23 bigha's land",
    imageUrl: "images/gopal.jpg",
  },
  {
    id: 7,
    parentId: "4",
    name: "Mukesh Hamad",
    positionName: "Accountant",
    wife: "Savita Hamad",
    father: "Narayan Hamad",
    mother: "Leela(Bhagu)  Hamad",
    phone: "9993330480",
    email: "mukeshhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "23/07/1993",
    dod: "live",
    // department: "Marketing",
    description:
      "Mukesh hamad is born in 23/07/1993. He is the eldest son of Narayan Hamad.He completed his graduation from DAVV in Commerce Stream .He is a Accountact by profession.He Specializes in Accountant Tally. He has One son .",
    imageUrl: "images/mukesh.jpg",
  },
  {
    id: 8,
    parentId: "4",
    name: "Ravi Hamad",
    positionName: "Tent House Shop",
    wife: "Indira Hamad",
    father: "Narayan Hamad",
    mother: "Leela(Bhagu)  Hamad",
    phone: "8085406591",
    email: "ravihamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "28/08/1995",
    dod: "live",
    description:
      "Ravi hamad is born in 28/08/1995. He is the youngest son of Narayan Hamad.He completed his graduation  in Maths Stream .He is a Owner of Sirvi Tent House And he is businessman by profession. He has One Daughter .",
    imageUrl: "images/ravi.jpg",
  },
  {
    id: 9,
    parentId: "5",
    name: "Lokesh  Hamad",
    positionName: "Child Water Plant",
    wife: "Payal (Neha) Hamad",
    father: "Mannalal Hamad",
    mother: "Leela  Hamad",
    phone: "9109400268",
    email: "lokeshhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "03/12/1997",
    dod: "live",
    description:
      "Lokesh hamad is born in 03/12/1997. He is the son of Mannalal Hamad.He completed his Studies till 12th. After that he started business of child water plant in 2018. he is businessman by profession. He is Owner of Mahi RO+UV Child Water ",
    imageUrl: "images/lokesh.jpg",
  },
  {
    id: 10,
    parentId: "6",
    name: "Harish Hamad",
    positionName: "Software Developer",
    wife: "Unmarried",
    father: "Gopal Hamad",
    mother: "Kanku  Hamad",
    phone: "9589352268",
    email: "harishhamad21@gmail.com",
    sex: "Male",
    team: "",
    dob: "19/08/2001",
    dod: "live",
    description:
      "Harish hamad is born in 19/08/2001. He is the son of Gopal Hamad.He completed his 12th From Agriculture. After that he got selected for Govt.ITI college from diesel mechanical branch .he did internship from Metalman pvt.ltd Pithampur. After the graduation from BSC Agriculture he switch his careere in Software engeenere and he learn  It codding Skill . After that he started Internship in Software developer from HPH technology Benglore(Karnataka). he is Software developer by profession.",
    imageUrl: "images/Harish.jpg",
  },
  {
    id: 11,
    parentId: "7",
    name: "Vaidik Hamad",
    positionName: "Student",
    wife: "Unmarried",
    father: "Mukesh Hamad",
    mother: "Savita  Hamad",
    phone: "9993330480",
    email: "vaidikhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "11/07/2016",
    dod: "live",
    description:
      "Vaidik Hamad is born in 11/07/2016. He is the son of Mukesh Hamad. Vaidik Hamad is a student of 4th class.",
    imageUrl: "images/vaidik.jpg",
  },
  {
    id: 12,
    parentId: "2",
    name: "Shankarlal Hamad",
    positionName: "Farmer",
    wife: "Dariyav Hamad",
    father: "Mangilal Hamad",
    mother: "Kanku  Hamad",
    phone: "none",
    email: "none",
    sex: "Male",
    team: "",
    dob: "Around 1957-57",
    dod: "11/01/2011",
    description:
      "Shankar Hamad was born around 1956-1957. He was eldest son of Mangilal Hamad .He was Farmer by profession. He has two sons and one daughter named Parvati(Pari).He has 4 bigha's land in his shares.Shankarlal passed away on 11/01/2013 suddenly of a heart attack.",
    imageUrl:
      "https://cdn.dribbble.com/users/1223630/screenshots/8115260/media/8145a871d9c4d67ec06e047ccc6574b4.gif",
  },
  {
    id: 13,
    parentId: "2",
    name: "Gendalal Hamad",
    positionName: "Farmer",
    wife: "Ganga Hamad",
    father: "Mangilal Hamad",
    mother: "Kanku  Hamad",
    phone: "none",
    email: "none",
    sex: "Male",
    team: "",
    dob: "Around 1965 or may be later",
    dod: "25/04/2015",
    description:
      "Gendalal Hamad was born around 1965 or may be later. He was youngest son of Mangilal Hamad .He was Farmer by profession. He has one sons and one daughter named Sapna.He has also 4 bigha's land in his shares. Gendalal passed away on 25/04/2015 due to disease of cancer",
    imageUrl:
      "https://cdn.dribbble.com/users/1223630/screenshots/8115260/media/8145a871d9c4d67ec06e047ccc6574b4.gif",
  },
  {
    id: 14,
    parentId: "2",
    name: "Kanjilal Hamad",
    positionName: "Farmer",
    wife: "no info",
    father: "Mangilal Hamad",
    mother: "Kanku  Hamad",
    phone: "none",
    email: "none",
    sex: "Male",
    team: "",
    dob: "No info.",
    dod: "Between 1975 to 1990",
    description:
      " Kanjilal was middle son of Mangilal Hamad .He was Farmer by profession. He has one daughter only. He has also 4 bigha's land in his shares.One day At the time of evening, while returning home from farming, he had gone to a nearby village to find laborers and was killed by thieves.",
    imageUrl:
      "https://cdn.dribbble.com/users/1223630/screenshots/8115260/media/8145a871d9c4d67ec06e047ccc6574b4.gif",
  },
  {
    id: 15,
    parentId: "12",
    name: "Dinesh Hamad",
    positionName: "Farmer",
    wife: "Kavita Hamad",
    father: "Shankarlal Hamad",
    mother: "Dariyav  Hamad",
    phone: "9752938949",
    email: "dineshhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "Around 1981 or may be later",
    dod: "living",
    description:
      "Dinesh Hamad is born around 1981 or may be later. He is eldest son of Shankarlal Hamad .He is Farmer by profession. He has one sons and one daughter named Lakshmi.He has also 2 bigha's land in his shares.Before He took interested in business he open dhaba in his villages but due to some personal problem he closed it and taking interested in faming With technologies",
    imageUrl: "images/dinesh.jpg",
  },
  {
    id: 16,
    parentId: "12",
    name: "Rameshwar Hamad",
    positionName: "Farmer",
    wife: "Babita Hamad",
    father: "Shankarlal Hamad",
    mother: "Dariyav  Hamad",
    phone: "9993339655",
    email: "rameshwarhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "Around 1985-86 or may be later",
    dod: "living",
    description:
      "Rameshwar Hamad is born around 1985-86 or may be later. He is youngest son of Shankarlal Hamad .He is Farmer by profession. He has one sons and Two daughter named Prachi and Nidhi.He has also 2 bigha's land in his shares.Currently he is taking interested in faming With  new technologies",
    imageUrl: "images/rameshwar.jpg",
  },
  {
    id: 17,
    parentId: "13",
    name: "Jagdish Hamad",
    positionName: "Farmer",
    wife: "Pooja Hamad",
    father: "Gendalal Hamad",
    mother: "Ganga  Hamad",
    phone: "9993929323",
    email: "jagdishhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "01/01/1996",
    dod: "living",
    description:
      "Jagdish Hamad is born around 01/01/1996. He is son of Gendalal Hamad. He studies till 10thor 12th. After that he took interested i farming. He is Farmer by profession. He has one sons. He has 4 bigha's land in his shares.",
    imageUrl: "images/jagdish.jpg",
  },
  {
    id: 18,
    parentId: "15",
    name: "Mahesh Hamad",
    positionName: "Student",
    wife: "Unmarried",
    father: "Dinesh Hamad",
    mother: "Kavita  Hamad",
    phone: "9893721981",
    email: "maheshhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "01/01/2003",
    dod: "living",
    description:
      "Mahesh Hamad is born on 01/01/2003. He is Son of Dinesh Hamad .He is Student and He has Completed 12th from Commerce.",
    imageUrl: "images/mahesh.jpg",
  },
  {
    id: 19,
    parentId: "16",
    name: "Aadarsh Hamad",
    positionName: "Student",
    wife: "Unmarried",
    father: "Rameshwar Hamad",
    mother: "Babita  Hamad",
    phone: "9993339655",
    email: "aadarshhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "05/07/2013",
    dod: "living",
    description:
      "Aadarsh Hamad is born on 05/07/2013. He is Son of Rameshwar Hamad .He is Student in 4th class .",
    imageUrl: "images/aadarsh.jpg",
  },
  {
    id: 20,
    parentId: "17",
    name: "Nidhesh Hamad",
    positionName: "Student",
    wife: "Unmarried",
    father: "Jagdish Hamad",
    mother: "Pooja  Hamad",
    phone: "9993929323",
    email: "nidheshhamad@gmail.com",
    sex: "Male",
    team: "",
    dob: "01/01/2015",
    dod: "living",
    description:
      "Nidhesh Hamad is born on 01/01/2015. He is Son of Jagdish Hamad .He is Student in 3rd class .",
    imageUrl:
      "https://cdn.dribbble.com/users/1223630/screenshots/8115260/media/8145a871d9c4d67ec06e047ccc6574b4.gif",
  },
];

export default employees;
